const folders = [
    {
        FolderID: 1,
        ParentFolderID: null,
        Name: 'Root',
        Path: '/Root',
        CreatedDate: '2023-10-01T09:00:00',
        ModifiedDate: '2023-10-01T09:00:00',
        'User ID': null,
        subfolders: [
            {
                FolderID: 2,
                ParentFolderID: 1,
                Name: 'Documents',
                Path: '/Root/Documents',
                CreatedDate: '2023-10-01T09:30:00',
                ModifiedDate: '2023-10-01T09:30:00',
                'User ID': null,
                subfolders: [
                    {
                        FolderID: 4,
                        ParentFolderID: 2,
                        Name: 'Work',
                        Path: '/Root/Documents/Work',
                        CreatedDate: '2023-10-01T10:00:00',
                        ModifiedDate: '2023-10-01T10:00:00',
                        'User ID': null,
                        files: [
                            {
                                FileID: 1,
                                FolderID: 4,
                                Name: 'Project_Plan.docx',
                                FileType: '.docx',
                                Size: 2048,
                                CreatedDate: '2023-10-01T10:00:00',
                                ModifiedDate: '2023-10-01T10:00:00',
                                'User ID': null,
                            },
                            {
                                FileID: 2,
                                FolderID: 4,
                                Name: 'Meeting_Notes.txt',
                                FileType: '.txt',
                                Size: 1024,
                                CreatedDate: '2023-10-02T11:00:00',
                                ModifiedDate: '2023-10-02T11:00:00',
                                'User ID': null,
                            },
                        ],
                    },
                    {
                        FolderID: 5,
                        ParentFolderID: 2,
                        Name: 'Personal',
                        Path: '/Root/Documents/Personal',
                        CreatedDate: '2023-10-01T10:15:00',
                        ModifiedDate: '2023-10-01T10:15:00',
                        'User ID': null,
                        files: [
                            {
                                FileID: 3,
                                FolderID: 5,
                                Name: 'Resume.pdf',
                                FileType: '.pdf',
                                Size: 5120,
                                CreatedDate: '2023-10-03T12:00:00',
                                ModifiedDate: '2023-10-03T12:00:00',
                                'User ID': null,
                            },
                        ],
                    },
                ],
            },
            {
                FolderID: 3,
                ParentFolderID: 1,
                Name: 'Images',
                Path: '/Root/Images',
                CreatedDate: '2023-10-01T09:45:00',
                ModifiedDate: '2023-10-01T09:45:00',
                'User ID': null,
                subfolders: [
                    {
                        FolderID: 6,
                        ParentFolderID: 3,
                        Name: 'Vacation',
                        Path: '/Root/Images/Vacation',
                        CreatedDate: '2023-10-01T10:30:00',
                        ModifiedDate: '2023-10-01T10:30:00',
                        'User ID': null,
                        files: [
                            {
                                FileID: 4,
                                FolderID: 6,
                                Name: 'Beach_Photos.zip',
                                FileType: '.zip',
                                Size: 2048000,
                                CreatedDate: '2023-10-04T13:00:00',
                                ModifiedDate: '2023-10-04T13:00:00',
                                'User ID': null,
                            },
                        ],
                    },
                ],
                files: [
                    {
                        FileID: 5,
                        FolderID: 3,
                        Name: 'Profile_Picture.jpg',
                        FileType: '.jpg',
                        Size: 204800,
                        CreatedDate: '2023-10-05T14:00:00',
                        ModifiedDate: '2023-10-05T14:00: 00',
                        'User  ID': null,
                    },
                ],
            },
        ],
    },
];
